refactor and new functionality
dpzi/task-list pull request #1
Opened 2023-02-15 10:55 UTC by dpzi

2023-02-16 11:22 UTC, AbhilashZemoso requested changes
TaskList class should be broken down to multiple classes to achieve Single Responsibility Principle

2023-02-17 04:16 UTC, AbhilashZemoso requested changes
use classes and interfaces for all functions

2023-02-17 04:20 UTC, dpzi commented
> use classes and interfaces for all functions

JavaScript is module based system I think using class based not good. https://dev.to/giantmachines/stop-using-javascript-classes-33ij

2023-02-17 04:32 UTC, AbhilashZemoso commented
> > use classes and interfaces for all functions
> 
> JavaScript is module based system I think using class based not good. https://dev.to/giantmachines/stop-using-javascript-classes-33ij

I agree, but for this assignment we need to implement SOLID principles which can be achieved using interfaces and classes. This is to showcase your understanding in SOLID, where language is just an option.

2023-02-17 04:33 UTC, dpzi commented
> > > use classes and interfaces for all functions
> > 
> > 
> > JavaScript is module based system I think using class based not good. https://dev.to/giantmachines/stop-using-javascript-classes-33ij
> 
> I agree, but for this assignment we need to implement SOLID principles which can be achieved using interfaces and classes. This is to showcase your understanding in SOLID, where language is just an option.

No issue i will convert all the files on class

2023-02-20 09:41 UTC, AbhilashZemoso commented on typescript/src/task_operations.ts
> +export class TaskOperations {
can you add a interface for this class, with all the method

2023-02-20 09:44 UTC, AbhilashZemoso commented on typescript/src/task_operations.ts
> +export class TaskOperations {
segregate the functions as much as possible in different classes  with individual interfaces

2023-02-20 09:44 UTC, AbhilashZemoso approved these changes
Work on the changes

2023-02-20 11:34 UTC, merged